# -*- coding: utf-8 -*-
"""GSoC-2022_JdeRobot_Python_Challenge.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NOSXWj7H_Txbn5OCHRzl6VKfMo1zk-wx
"""

from matplotlib import rc
rc('animation', html='jshtml')

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

fig = plt.figure(figsize=(5, 5))
ax = plt.axes()
ax.get_xaxis().set_visible(False)
ax.get_yaxis().set_visible(False)

x = 5 * np.random.random_sample()
y = 5 * np.random.random_sample()

vx = np.random.random_sample() / 5
vy = np.random.random_sample() / 5

def frame(f):
    ax.clear()
    global x, y, vx, vy
    if x < 0.1 or x >= 4.9:
        vx *= -1
    if y < 0.1 or y >= 4.9:
        vy *= -1
    x += vx
    y += vy

    plt.title("Brownian Motion")
    ax.set_xlim(0,5)
    ax.set_ylim(0,5)
    plot = ax.scatter(x, y, c='b')
    return plot

anim = animation.FuncAnimation(fig, frame, frames=200, blit=False, repeat=True, interval=50)
anim

gif = anim.save('BrownianMotion.gif', writer = "pillow", fps=10)
gif

